server:
  port: 8000
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring:
  application:
    name: drone-delivery-app
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

